# Data Check

In [2]:
import sys, os
sys.path.insert(0, os.path.join(os.getcwd(), '..', 'src'))
sys.path.insert(0, os.path.join(os.getcwd(), '..'))

import pandas as pd
from sqlalchemy import text
import database as db

pd.set_option('display.max_colwidth', 100)

## 1. Load all raw rows into a dataframe

In [4]:
with db.get_connection() as conn:
    df = pd.read_sql(text('SELECT id, title, content, date, link FROM scraped_news'), conn)

print(f'Total rows: {len(df)}')
df.head()

Total rows: 16794

,id,title,content,date,link
0,1,CCID obtains 90-day detention order for drug trafficker Shiran Basik,The Central Criminal Investigation Department (CCID) has obtained approval to detain 48-year-old...,17 Aug 2026,https://www.dailymirror.lk/breaking-news/CCID-obtains-90-day-detention-order-for-drug-trafficker...
1,2,Colombo port under threat? Galathea is the warning shot,"Colombo has the port. India has the cargo. With nearly, Sri Lanka’s record-breaking port perform...",17 Aug 2026,https://www.dailymirror.lk/breaking-news/Colombo-port-under-threat-Galathea-is-the-warning-shot/...
2,3,"Sri Lanka CERT warns of scam impersonating Central Bank, police officials",Sri Lanka CERT has warned the public about a sophisticated fraud scheme in which scammers impers...,17 Aug 2026,https://www.dailymirror.lk/breaking-news/Sri-Lanka-CERT-warns-of-scam-impersonating-Central-Bank...
3,4,Does the Public Have Any Say in Sri Lanka's Budget? The Score Is 9 Out of 100,"Sri Lanka is making notable progress in publishing fiscal data, yet ordinary citizens remain alm...",17 Aug 2026,https://www.dailymirror.lk/breaking-news/Does-the-Public-Have-Any-Say-in-Sri-Lanka-s-Budget-The-...
4,5,Trump orders Pentagon to cut back military exercises with South Korea,U.S. President Donald Trump on Sunday instructed the Pentagon to ’’substantially reduce’’ ​joint...,17 Aug 2026,https://www.dailymirror.lk/breaking-news/Trump-orders-Pentagon-to-cut-back-military-exercises-wi...

## 2. Basic null / empty checks

In [5]:
checks = pd.DataFrame({
    'null_count': df.isnull().sum(),
    'empty_string_count': (df.astype(str).apply(lambda col: (col.str.strip() == '').sum()))
})
checks

         null_count  empty_string_count
id                0                   0
title             0                   0
content           0                   0
date              0                   0
link              0                   0

## 3. Content length distribution

In [6]:
df['content_len_chars'] = df['content'].astype(str).str.len()
print(df['content_len_chars'].describe())

import config
short = df[df['content_len_chars'] < config.MIN_CONTENT_LENGTH_CHARS]
print(f"\nRows below MIN_CONTENT_LENGTH_CHARS ({config.MIN_CONTENT_LENGTH_CHARS} chars): {len(short)}")
short[['id', 'title', 'content_len_chars']].head(20)

count    16794.000000
mean       206.056806
std         63.301414
min          3.000000
25%        161.000000
50%        198.000000
75%        242.000000
max        450.000000
Name: content_len_chars, dtype: float64

Rows below MIN_CONTENT_LENGTH_CHARS (50 chars): 2

,id,title,content_len_chars
2727,2728,Sri Lanka Schools Dialog Under-19 League Rugby Tournament 2026,40
6353,6354,Shanaka Rewrites Record Books with 19-Ball Fifty,3

## 4. Distinct date value patterns

In [7]:
print(f"Distinct raw date values: {df['date'].nunique()} (out of {len(df)} rows)")
df['date'].value_counts().head(30)

Distinct raw date values: 571 (out of 16794 rows)

date
27 Nov 2025    76
08 Jul 2026    75
29 Nov 2025    72
28 Nov 2025    63
02 Jul 2026    62
09 Apr 2026    61
19 May 2026    60
08 Apr 2026    59
05 Aug 2026    58
25 Jun 2026    57
01 Dec 2025    57
05 Dec 2025    56
07 Aug 2026    55
17 Mar 2026    55
03 Dec 2025    55
16 Jun 2026    55
09 Jun 2026    55
18 Jun 2026    54
06 Aug 2026    54
25 Mar 2026    53
10 Sep 2025    53
01 Jul 2026    52
07 Jul 2026    52
17 Jun 2026    52
19 Dec 2025    52
11 Nov 2025    51
30 Sep 2025    51
04 Aug 2026    51
26 May 2026    51
02 Dec 2025    50
Name: count, dtype: int64

In [ ]:

import re

def date_pattern(val):
    s = str(val).strip()
    if re.fullmatch(r'\d{4}-\d{2}-\d{2}.*', s):
        return 'ISO_DATE (YYYY-MM-DD...)'
    if re.fullmatch(r'\d+\s+hours?\s+ago', s, re.IGNORECASE):
        return 'N hours ago'
    if re.fullmatch(r'\d+\s+days?\s+ago', s, re.IGNORECASE):
        return 'N days ago'
    if re.fullmatch(r'\d+\s+minutes?\s+ago', s, re.IGNORECASE):
        return 'N minutes ago'
    if s.lower() in ('yesterday', 'today'):
        return 'Yesterday/Today keyword'
    if re.fullmatch(r'[A-Za-z]+\s+\d{1,2},?\s+\d{4}', s):
        return 'Month DD, YYYY'
    if s == '' or s.lower() == 'none' or s.lower() == 'nan':
        return 'EMPTY/NULL'
    return 'OTHER/UNRECOGNIZED'

df['date_pattern'] = df['date'].apply(date_pattern)
pattern_counts = df['date_pattern'].value_counts()
print(pattern_counts)
print(f"\nTotal patterns found: {len(pattern_counts)}")

date_pattern
OTHER/UNRECOGNIZED    16794
Name: count, dtype: int64

Total patterns found: 1

In [ ]:
# Show a few real examples from each pattern bucket, especially OTHER/UNRECOGNIZED —
# these are the values date_processing.py needs explicit handling for.
for pattern in df['date_pattern'].unique():
    examples = df[df['date_pattern'] == pattern]['date'].unique()[:5]
    print(f"--- {pattern} ---")
    for ex in examples:
        print(f"  {ex!r}")
    print()

--- OTHER/UNRECOGNIZED ---
  '17 Aug 2026'
  '16 Aug 2026'
  '15 Aug 2026'
  '14 Aug 2026'
  '13 Aug 2026'

## 5. Duplicate detection preview

In [10]:
dup_links = df[df.duplicated(subset=['link'], keep=False)].sort_values('link')
print(f"Rows sharing a duplicate link: {len(dup_links)}")
dup_links[['id', 'title', 'link']].head(20)

Rows sharing a duplicate link: 0

Empty DataFrame
Columns: [id, title, link]
Index: []

In [11]:
dup_titles = df[df.duplicated(subset=['title'], keep=False)].sort_values('title')
print(f"Rows sharing an exact duplicate title: {len(dup_titles)}")
dup_titles[['id', 'title', 'date']].head(20)

Rows sharing an exact duplicate title: 87

,id,title,date
13913,13914,2023 Grade five scholarship exam: Cut-off marks released,02 Feb 2024
15577,15578,2023 Grade five scholarship exam: Cut-off marks released,17 Nov 2023
16246,16247,A 15-hour water cut in Colombo,21 Oct 2023
13738,13739,A 15-hour water cut in Colombo,09 Feb 2024
13581,13582,Ambitious plans underway to make SL a ‘happening’ tourist destination,15 Feb 2024
13560,13561,Ambitious plans underway to make SL a ‘happening’ tourist destination,16 Feb 2024
13491,13492,"Apply directly to respective schools, excluding grades 1, 5, 6, and A/L",19 Feb 2024
14150,14151,"Apply directly to respective schools, excluding grades 1, 5, 6, and A/L",23 Jan 2024
15393,15394,CBSL further reduces policy interest rates,24 Nov 2023
16622,16623,CBSL further reduces policy interest rates,05 Oct 2023
14499,14500,Chicken prices reduced by Rs. 40,06 Jan 2024
12786,12787,Chicken prices reduced by Rs. 40,20 Mar 2024
2107,2108,Court dismisses Daya Group’s writ application against People’s Bank auction,20 Jun 2026
2112,2113,Court dismisses Daya Group’s writ application against People’s Bank auction,20 Jun 2026
456,457,Daily Mirror report comes to limelight in Parliament,04 Aug 2026
5330,5331,Daily Mirror report comes to limelight in Parliament,17 Mar 2026
7217,7218,Daily Mirror warns public of fake article circulating on social media,12 Jan 2026
7969,7970,Daily Mirror warns public of fake article circulating on social media,18 Dec 2025
2071,2072,Emotional Chamari takes blame for Sri Lanka loss at T20WC,22 Jun 2026
2048,2049,Emotional Chamari takes blame for Sri Lanka loss at T20WC,22 Jun 2026

## 6. Summary

In [12]:
print('=== SUMMARY ===')
print(f"Total rows: {len(df)}")
print(f"Rows with null/empty content: {(df['content'].astype(str).str.strip() == '').sum()}")
print(f"Rows below min content length: {len(short)}")
print(f"Distinct date patterns found: {len(pattern_counts)}")
print(f"Rows with duplicate links: {len(dup_links)}")
print(f"Rows with duplicate titles: {len(dup_titles)}")
print()
print('Date patterns breakdown:')
print(pattern_counts)

=== SUMMARY ===
Total rows: 16794
Rows with null/empty content: 0
Rows below min content length: 2
Distinct date patterns found: 1
Rows with duplicate links: 0
Rows with duplicate titles: 87

Date patterns breakdown:
date_pattern
OTHER/UNRECOGNIZED    16794
Name: count, dtype: int64

In [13]:
for val in df['date'].head(20):
    print(repr(val))

'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'
'17 Aug 2026'

In [14]:
print(f"Distinct actual date values: {df['date'].nunique()}")
df['date'].value_counts().head(20)

Distinct actual date values: 571

date
27 Nov 2025    76
08 Jul 2026    75
29 Nov 2025    72
28 Nov 2025    63
02 Jul 2026    62
09 Apr 2026    61
19 May 2026    60
08 Apr 2026    59
05 Aug 2026    58
25 Jun 2026    57
01 Dec 2025    57
05 Dec 2025    56
07 Aug 2026    55
17 Mar 2026    55
03 Dec 2025    55
16 Jun 2026    55
09 Jun 2026    55
18 Jun 2026    54
06 Aug 2026    54
25 Mar 2026    53
Name: count, dtype: int64

In [15]:
print(f"Total rows: {len(df)}")
print(f"Distinct date values: {df['date'].nunique()}")

parsed = pd.to_datetime(df['date'], format='%d %b %Y')
print(f"Date range: {parsed.min().date()} to {parsed.max().date()}")
print(f"Span: {(parsed.max() - parsed.min()).days} days")
print()

# re-check data quality on the full refreshed set
print(f"Null/empty content: {(df['content'].astype(str).str.strip() == '').sum()}")
print(f"Duplicate links: {df.duplicated(subset=['link'], keep=False).sum()}")
print(f"Duplicate titles: {df.duplicated(subset=['title'], keep=False).sum()}")
print()

# articles per week, to sanity-check there are no big gaps
weekly = parsed.dt.to_period('W').value_counts().sort_index()
print("Weeks with fewest articles (checking for gaps):")
print(weekly.sort_values().head(10))

Total rows: 16794
Distinct date values: 571
Date range: 2023-09-28 to 2026-08-17
Span: 1054 days

Null/empty content: 0
Duplicate links: 0
Duplicate titles: 87

Weeks with fewest articles (checking for gaps):
date
2026-08-17/2026-08-23     27
2025-07-21/2025-07-27     40
2023-09-25/2023-10-01     68
2023-12-25/2023-12-31     86
2025-10-20/2025-10-26     86
2024-04-22/2024-04-28     88
2024-01-08/2024-01-14    120
2025-11-03/2025-11-09    125
2024-04-01/2024-04-07    130
2024-03-25/2024-03-31    139
Freq: W-SUN, Name: count, dtype: int64

In [16]:
# check every distinct date value actually matches DD Mon YYYY — flag anything that doesn't
import re
pattern = re.compile(r'^\d{2} [A-Za-z]{3} \d{4}$')
bad_formats = df[~df['date'].astype(str).str.match(pattern)]
print(f"Rows NOT matching 'DD Mon YYYY': {len(bad_formats)}")
if len(bad_formats) > 0:
    print(bad_formats['date'].unique()[:20])

Rows NOT matching 'DD Mon YYYY': 0

In [2]:
import sys, os
sys.path.insert(0, os.path.join(os.getcwd(), '..', 'src'))
sys.path.insert(0, os.path.join(os.getcwd(), '..'))

import pipeline

In [3]:
pipeline.process_existing_articles(batch_size=20)

2026-08-18 02:08:07 | INFO | pipeline | process_existing_articles: 16794 articles to process
2026-08-18 02:08:08 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 20/16794 (completed=20, failed=0)

2026-08-18 02:08:09 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 40/16794 (completed=40, failed=0)

2026-08-18 02:08:10 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 60/16794 (completed=60, failed=0)

2026-08-18 02:08:11 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 80/16794 (completed=80, failed=0)

2026-08-18 02:08:11 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 100/16794 (completed=100, failed=0)

2026-08-18 02:08:12 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 120/16794 (completed=120, failed=0)

2026-08-18 02:08:13 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 140/16794 (completed=140, failed=0)

2026-08-18 02:08:14 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 160/16794 (completed=160, failed=0)

2026-08-18 02:08:15 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 180/16794 (completed=180, failed=0)

2026-08-18 02:08:15 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 200/16794 (completed=200, failed=0)

2026-08-18 02:08:16 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 220/16794 (completed=220, failed=0)

2026-08-18 02:08:17 | INFO | deduplication | Deduplication results: {'UNIQUE': 19, 'NEAR_DUPLICATE': 1}

  Progress: 240/16794 (completed=240, failed=0)

2026-08-18 02:08:17 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 260/16794 (completed=260, failed=0)

2026-08-18 02:08:18 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 280/16794 (completed=280, failed=0)

2026-08-18 02:08:18 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 300/16794 (completed=300, failed=0)

2026-08-18 02:08:19 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 320/16794 (completed=320, failed=0)

2026-08-18 02:08:20 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 340/16794 (completed=340, failed=0)

2026-08-18 02:08:20 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 360/16794 (completed=360, failed=0)

2026-08-18 02:08:21 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 380/16794 (completed=380, failed=0)

2026-08-18 02:08:21 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 400/16794 (completed=400, failed=0)

2026-08-18 02:08:22 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 420/16794 (completed=420, failed=0)

2026-08-18 02:08:23 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 440/16794 (completed=440, failed=0)

2026-08-18 02:08:23 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 460/16794 (completed=460, failed=0)

2026-08-18 02:08:24 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 480/16794 (completed=480, failed=0)

2026-08-18 02:08:25 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 500/16794 (completed=500, failed=0)

2026-08-18 02:08:25 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 520/16794 (completed=520, failed=0)

2026-08-18 02:08:26 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 540/16794 (completed=540, failed=0)

2026-08-18 02:08:26 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 560/16794 (completed=560, failed=0)

2026-08-18 02:08:27 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 580/16794 (completed=580, failed=0)

2026-08-18 02:08:28 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 600/16794 (completed=600, failed=0)

2026-08-18 02:08:28 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 620/16794 (completed=620, failed=0)

2026-08-18 02:08:29 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 640/16794 (completed=640, failed=0)

2026-08-18 02:08:30 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 660/16794 (completed=660, failed=0)

2026-08-18 02:08:30 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 680/16794 (completed=680, failed=0)

2026-08-18 02:08:31 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 700/16794 (completed=700, failed=0)

2026-08-18 02:08:32 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 720/16794 (completed=720, failed=0)

2026-08-18 02:08:32 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 740/16794 (completed=740, failed=0)

2026-08-18 02:08:33 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 760/16794 (completed=760, failed=0)

2026-08-18 02:08:33 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 780/16794 (completed=780, failed=0)

2026-08-18 02:08:34 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 800/16794 (completed=800, failed=0)

2026-08-18 02:08:35 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 820/16794 (completed=820, failed=0)

2026-08-18 02:08:35 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 840/16794 (completed=840, failed=0)

2026-08-18 02:08:36 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 860/16794 (completed=860, failed=0)

2026-08-18 02:08:36 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 880/16794 (completed=880, failed=0)

2026-08-18 02:08:37 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 900/16794 (completed=900, failed=0)

2026-08-18 02:08:38 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 920/16794 (completed=920, failed=0)

2026-08-18 02:08:38 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 940/16794 (completed=940, failed=0)

2026-08-18 02:08:39 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 960/16794 (completed=960, failed=0)

2026-08-18 02:08:40 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 980/16794 (completed=980, failed=0)

2026-08-18 02:08:40 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1000/16794 (completed=1000, failed=0)

2026-08-18 02:08:41 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1020/16794 (completed=1020, failed=0)

2026-08-18 02:08:42 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1040/16794 (completed=1040, failed=0)

2026-08-18 02:08:42 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1060/16794 (completed=1060, failed=0)

2026-08-18 02:08:43 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1080/16794 (completed=1080, failed=0)

2026-08-18 02:08:44 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1100/16794 (completed=1100, failed=0)

2026-08-18 02:08:44 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1120/16794 (completed=1120, failed=0)

2026-08-18 02:08:45 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1140/16794 (completed=1140, failed=0)

2026-08-18 02:08:45 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1160/16794 (completed=1160, failed=0)

2026-08-18 02:08:46 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1180/16794 (completed=1180, failed=0)

2026-08-18 02:08:47 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1200/16794 (completed=1200, failed=0)

2026-08-18 02:08:47 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1220/16794 (completed=1220, failed=0)

2026-08-18 02:08:48 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1240/16794 (completed=1240, failed=0)

2026-08-18 02:08:49 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1260/16794 (completed=1260, failed=0)

2026-08-18 02:08:49 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1280/16794 (completed=1280, failed=0)

2026-08-18 02:08:50 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1300/16794 (completed=1300, failed=0)

2026-08-18 02:08:51 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1320/16794 (completed=1320, failed=0)

2026-08-18 02:08:52 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1340/16794 (completed=1340, failed=0)

2026-08-18 02:08:52 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1360/16794 (completed=1360, failed=0)

2026-08-18 02:08:53 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1380/16794 (completed=1380, failed=0)

2026-08-18 02:08:54 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1400/16794 (completed=1400, failed=0)

2026-08-18 02:08:54 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1420/16794 (completed=1420, failed=0)

2026-08-18 02:08:55 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1440/16794 (completed=1440, failed=0)

2026-08-18 02:08:56 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1460/16794 (completed=1460, failed=0)

2026-08-18 02:08:56 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1480/16794 (completed=1480, failed=0)

2026-08-18 02:08:57 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1500/16794 (completed=1500, failed=0)

2026-08-18 02:08:58 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1520/16794 (completed=1520, failed=0)

2026-08-18 02:08:58 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1540/16794 (completed=1540, failed=0)

2026-08-18 02:08:59 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1560/16794 (completed=1560, failed=0)

2026-08-18 02:09:00 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1580/16794 (completed=1580, failed=0)

2026-08-18 02:09:00 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1600/16794 (completed=1600, failed=0)

2026-08-18 02:09:01 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1620/16794 (completed=1620, failed=0)

2026-08-18 02:09:02 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1640/16794 (completed=1640, failed=0)

2026-08-18 02:09:02 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1660/16794 (completed=1660, failed=0)

2026-08-18 02:09:03 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1680/16794 (completed=1680, failed=0)

2026-08-18 02:09:04 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1700/16794 (completed=1700, failed=0)

2026-08-18 02:09:04 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1720/16794 (completed=1720, failed=0)

2026-08-18 02:09:05 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1740/16794 (completed=1740, failed=0)

2026-08-18 02:09:05 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1760/16794 (completed=1760, failed=0)

2026-08-18 02:09:06 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1780/16794 (completed=1780, failed=0)

2026-08-18 02:09:07 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1800/16794 (completed=1800, failed=0)

2026-08-18 02:09:07 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1820/16794 (completed=1820, failed=0)

2026-08-18 02:09:08 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1840/16794 (completed=1840, failed=0)

2026-08-18 02:09:09 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1860/16794 (completed=1860, failed=0)

2026-08-18 02:09:09 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1880/16794 (completed=1880, failed=0)

2026-08-18 02:09:10 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1900/16794 (completed=1900, failed=0)

2026-08-18 02:09:11 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1920/16794 (completed=1920, failed=0)

2026-08-18 02:09:11 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1940/16794 (completed=1940, failed=0)

2026-08-18 02:09:12 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1960/16794 (completed=1960, failed=0)

2026-08-18 02:09:13 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 1980/16794 (completed=1980, failed=0)

2026-08-18 02:09:13 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2000/16794 (completed=2000, failed=0)

2026-08-18 02:09:14 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2020/16794 (completed=2020, failed=0)

2026-08-18 02:09:15 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2040/16794 (completed=2040, failed=0)

2026-08-18 02:09:16 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2060/16794 (completed=2060, failed=0)

2026-08-18 02:09:16 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2080/16794 (completed=2080, failed=0)

2026-08-18 02:09:17 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2100/16794 (completed=2100, failed=0)

2026-08-18 02:09:17 | INFO | deduplication | Deduplication results: {'UNIQUE': 19, 'NEAR_DUPLICATE': 1}

  Progress: 2120/16794 (completed=2120, failed=0)

2026-08-18 02:09:18 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2140/16794 (completed=2140, failed=0)

2026-08-18 02:09:19 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2160/16794 (completed=2160, failed=0)

2026-08-18 02:09:19 | INFO | deduplication | Deduplication results: {'UNIQUE': 19, 'EXACT_DUPLICATE': 1}

  Progress: 2180/16794 (completed=2180, failed=0)

2026-08-18 02:09:20 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2200/16794 (completed=2200, failed=0)

2026-08-18 02:09:20 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2220/16794 (completed=2220, failed=0)

2026-08-18 02:09:21 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2240/16794 (completed=2240, failed=0)

2026-08-18 02:09:22 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2260/16794 (completed=2260, failed=0)

2026-08-18 02:09:22 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2280/16794 (completed=2280, failed=0)

2026-08-18 02:09:24 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2300/16794 (completed=2300, failed=0)

2026-08-18 02:09:24 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2320/16794 (completed=2320, failed=0)

2026-08-18 02:09:25 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2340/16794 (completed=2340, failed=0)

2026-08-18 02:09:26 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2360/16794 (completed=2360, failed=0)

2026-08-18 02:09:26 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2380/16794 (completed=2380, failed=0)

2026-08-18 02:09:27 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2400/16794 (completed=2400, failed=0)

2026-08-18 02:09:28 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2420/16794 (completed=2420, failed=0)

2026-08-18 02:09:28 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2440/16794 (completed=2440, failed=0)

2026-08-18 02:09:29 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2460/16794 (completed=2460, failed=0)

2026-08-18 02:09:30 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2480/16794 (completed=2480, failed=0)

2026-08-18 02:09:30 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2500/16794 (completed=2500, failed=0)

2026-08-18 02:09:31 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2520/16794 (completed=2520, failed=0)

2026-08-18 02:09:32 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2540/16794 (completed=2540, failed=0)

2026-08-18 02:09:33 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2560/16794 (completed=2560, failed=0)

2026-08-18 02:09:33 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2580/16794 (completed=2580, failed=0)

2026-08-18 02:09:34 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2600/16794 (completed=2600, failed=0)

2026-08-18 02:09:35 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2620/16794 (completed=2620, failed=0)

2026-08-18 02:09:35 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2640/16794 (completed=2640, failed=0)

2026-08-18 02:09:36 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2660/16794 (completed=2660, failed=0)

2026-08-18 02:09:37 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2680/16794 (completed=2680, failed=0)

2026-08-18 02:09:37 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2700/16794 (completed=2700, failed=0)

2026-08-18 02:09:38 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2720/16794 (completed=2720, failed=0)

2026-08-18 02:09:39 | INFO | deduplication | Deduplication results: {'UNIQUE': 19}

  Progress: 2740/16794 (completed=2739, failed=1)

2026-08-18 02:09:39 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2760/16794 (completed=2759, failed=1)

2026-08-18 02:09:40 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2780/16794 (completed=2779, failed=1)

2026-08-18 02:09:40 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2800/16794 (completed=2799, failed=1)

2026-08-18 02:09:41 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2820/16794 (completed=2819, failed=1)

2026-08-18 02:09:42 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2840/16794 (completed=2839, failed=1)

2026-08-18 02:09:42 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2860/16794 (completed=2859, failed=1)

2026-08-18 02:09:43 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2880/16794 (completed=2879, failed=1)

2026-08-18 02:09:43 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2900/16794 (completed=2899, failed=1)

2026-08-18 02:09:44 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2920/16794 (completed=2919, failed=1)

2026-08-18 02:09:45 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2940/16794 (completed=2939, failed=1)

2026-08-18 02:09:46 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2960/16794 (completed=2959, failed=1)

2026-08-18 02:09:47 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 2980/16794 (completed=2979, failed=1)

2026-08-18 02:09:48 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3000/16794 (completed=2999, failed=1)

2026-08-18 02:09:48 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3020/16794 (completed=3019, failed=1)

2026-08-18 02:09:49 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3040/16794 (completed=3039, failed=1)

2026-08-18 02:09:50 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3060/16794 (completed=3059, failed=1)

2026-08-18 02:09:51 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3080/16794 (completed=3079, failed=1)

2026-08-18 02:09:52 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3100/16794 (completed=3099, failed=1)

2026-08-18 02:09:52 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3120/16794 (completed=3119, failed=1)

2026-08-18 02:09:53 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3140/16794 (completed=3139, failed=1)

2026-08-18 02:09:54 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3160/16794 (completed=3159, failed=1)

2026-08-18 02:09:54 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3180/16794 (completed=3179, failed=1)

2026-08-18 02:09:55 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3200/16794 (completed=3199, failed=1)

2026-08-18 02:09:55 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3220/16794 (completed=3219, failed=1)

2026-08-18 02:09:56 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3240/16794 (completed=3239, failed=1)

2026-08-18 02:09:57 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3260/16794 (completed=3259, failed=1)

2026-08-18 02:09:57 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3280/16794 (completed=3279, failed=1)

2026-08-18 02:09:58 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3300/16794 (completed=3299, failed=1)

2026-08-18 02:09:59 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3320/16794 (completed=3319, failed=1)

2026-08-18 02:09:59 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3340/16794 (completed=3339, failed=1)

2026-08-18 02:10:00 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3360/16794 (completed=3359, failed=1)

2026-08-18 02:10:01 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3380/16794 (completed=3379, failed=1)

2026-08-18 02:10:02 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3400/16794 (completed=3399, failed=1)

2026-08-18 02:10:03 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3420/16794 (completed=3419, failed=1)

2026-08-18 02:10:05 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3440/16794 (completed=3439, failed=1)

2026-08-18 02:10:06 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3460/16794 (completed=3459, failed=1)

2026-08-18 02:10:07 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3480/16794 (completed=3479, failed=1)

2026-08-18 02:10:08 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3500/16794 (completed=3499, failed=1)

2026-08-18 02:10:09 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3520/16794 (completed=3519, failed=1)

2026-08-18 02:10:09 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3540/16794 (completed=3539, failed=1)

2026-08-18 02:10:10 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3560/16794 (completed=3559, failed=1)

2026-08-18 02:10:11 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3580/16794 (completed=3579, failed=1)

2026-08-18 02:10:11 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3600/16794 (completed=3599, failed=1)

2026-08-18 02:10:12 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3620/16794 (completed=3619, failed=1)

2026-08-18 02:10:13 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3640/16794 (completed=3639, failed=1)

2026-08-18 02:10:13 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3660/16794 (completed=3659, failed=1)

2026-08-18 02:10:14 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3680/16794 (completed=3679, failed=1)

2026-08-18 02:10:15 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3700/16794 (completed=3699, failed=1)

2026-08-18 02:10:15 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3720/16794 (completed=3719, failed=1)

2026-08-18 02:10:16 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3740/16794 (completed=3739, failed=1)

2026-08-18 02:10:16 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3760/16794 (completed=3759, failed=1)

2026-08-18 02:10:17 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3780/16794 (completed=3779, failed=1)

2026-08-18 02:10:17 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3800/16794 (completed=3799, failed=1)

2026-08-18 02:10:18 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3820/16794 (completed=3819, failed=1)

2026-08-18 02:10:19 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3840/16794 (completed=3839, failed=1)

2026-08-18 02:10:19 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3860/16794 (completed=3859, failed=1)

2026-08-18 02:10:20 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3880/16794 (completed=3879, failed=1)

2026-08-18 02:10:21 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3900/16794 (completed=3899, failed=1)

2026-08-18 02:10:21 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3920/16794 (completed=3919, failed=1)

2026-08-18 02:10:22 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3940/16794 (completed=3939, failed=1)

2026-08-18 02:10:23 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3960/16794 (completed=3959, failed=1)

2026-08-18 02:10:23 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 3980/16794 (completed=3979, failed=1)

2026-08-18 02:10:24 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4000/16794 (completed=3999, failed=1)

2026-08-18 02:10:25 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4020/16794 (completed=4019, failed=1)

2026-08-18 02:10:25 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4040/16794 (completed=4039, failed=1)

2026-08-18 02:10:26 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4060/16794 (completed=4059, failed=1)

2026-08-18 02:10:27 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4080/16794 (completed=4079, failed=1)

2026-08-18 02:10:27 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4100/16794 (completed=4099, failed=1)

2026-08-18 02:10:28 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4120/16794 (completed=4119, failed=1)

2026-08-18 02:10:28 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4140/16794 (completed=4139, failed=1)

2026-08-18 02:10:29 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4160/16794 (completed=4159, failed=1)

2026-08-18 02:10:29 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4180/16794 (completed=4179, failed=1)

2026-08-18 02:10:31 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4200/16794 (completed=4199, failed=1)

2026-08-18 02:10:31 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4220/16794 (completed=4219, failed=1)

2026-08-18 02:10:32 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4240/16794 (completed=4239, failed=1)

2026-08-18 02:10:33 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4260/16794 (completed=4259, failed=1)

2026-08-18 02:10:33 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4280/16794 (completed=4279, failed=1)

2026-08-18 02:10:34 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4300/16794 (completed=4299, failed=1)

2026-08-18 02:10:35 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4320/16794 (completed=4319, failed=1)

2026-08-18 02:10:35 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4340/16794 (completed=4339, failed=1)

2026-08-18 02:10:36 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4360/16794 (completed=4359, failed=1)

2026-08-18 02:10:37 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4380/16794 (completed=4379, failed=1)

2026-08-18 02:10:40 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4400/16794 (completed=4399, failed=1)

2026-08-18 02:10:40 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4420/16794 (completed=4419, failed=1)

2026-08-18 02:10:41 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4440/16794 (completed=4439, failed=1)

2026-08-18 02:10:41 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4460/16794 (completed=4459, failed=1)

2026-08-18 02:10:42 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4480/16794 (completed=4479, failed=1)

2026-08-18 02:10:43 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4500/16794 (completed=4499, failed=1)

2026-08-18 02:10:43 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4520/16794 (completed=4519, failed=1)

2026-08-18 02:10:44 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4540/16794 (completed=4539, failed=1)

2026-08-18 02:10:44 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4560/16794 (completed=4559, failed=1)

2026-08-18 02:10:45 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4580/16794 (completed=4579, failed=1)

2026-08-18 02:10:46 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4600/16794 (completed=4599, failed=1)

2026-08-18 02:10:46 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4620/16794 (completed=4619, failed=1)

2026-08-18 02:10:47 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4640/16794 (completed=4639, failed=1)

2026-08-18 02:10:48 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4660/16794 (completed=4659, failed=1)

2026-08-18 02:10:48 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4680/16794 (completed=4679, failed=1)

2026-08-18 02:10:49 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4700/16794 (completed=4699, failed=1)

2026-08-18 02:10:49 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4720/16794 (completed=4719, failed=1)

2026-08-18 02:10:50 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4740/16794 (completed=4739, failed=1)

2026-08-18 02:10:51 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4760/16794 (completed=4759, failed=1)

2026-08-18 02:10:51 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4780/16794 (completed=4779, failed=1)

2026-08-18 02:10:52 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4800/16794 (completed=4799, failed=1)

2026-08-18 02:10:53 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4820/16794 (completed=4819, failed=1)

2026-08-18 02:10:53 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4840/16794 (completed=4839, failed=1)

2026-08-18 02:10:54 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4860/16794 (completed=4859, failed=1)

2026-08-18 02:10:54 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4880/16794 (completed=4879, failed=1)

2026-08-18 02:10:55 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4900/16794 (completed=4899, failed=1)

2026-08-18 02:10:56 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4920/16794 (completed=4919, failed=1)

2026-08-18 02:10:56 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4940/16794 (completed=4939, failed=1)

2026-08-18 02:10:57 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4960/16794 (completed=4959, failed=1)

2026-08-18 02:10:58 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 4980/16794 (completed=4979, failed=1)

2026-08-18 02:10:58 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5000/16794 (completed=4999, failed=1)

2026-08-18 02:10:59 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5020/16794 (completed=5019, failed=1)

2026-08-18 02:11:00 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5040/16794 (completed=5039, failed=1)

2026-08-18 02:11:00 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5060/16794 (completed=5059, failed=1)

2026-08-18 02:11:01 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5080/16794 (completed=5079, failed=1)

2026-08-18 02:11:01 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5100/16794 (completed=5099, failed=1)

2026-08-18 02:11:02 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5120/16794 (completed=5119, failed=1)

2026-08-18 02:11:02 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5140/16794 (completed=5139, failed=1)

2026-08-18 02:11:03 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5160/16794 (completed=5159, failed=1)

2026-08-18 02:11:04 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5180/16794 (completed=5179, failed=1)

2026-08-18 02:11:05 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5200/16794 (completed=5199, failed=1)

2026-08-18 02:11:06 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5220/16794 (completed=5219, failed=1)

2026-08-18 02:11:06 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5240/16794 (completed=5239, failed=1)

2026-08-18 02:11:07 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5260/16794 (completed=5259, failed=1)

2026-08-18 02:11:08 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5280/16794 (completed=5279, failed=1)

2026-08-18 02:11:08 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5300/16794 (completed=5299, failed=1)

2026-08-18 02:11:09 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5320/16794 (completed=5319, failed=1)

2026-08-18 02:11:09 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5340/16794 (completed=5339, failed=1)

2026-08-18 02:11:10 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5360/16794 (completed=5359, failed=1)

2026-08-18 02:11:10 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5380/16794 (completed=5379, failed=1)

2026-08-18 02:11:11 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5400/16794 (completed=5399, failed=1)

2026-08-18 02:11:12 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5420/16794 (completed=5419, failed=1)

2026-08-18 02:11:12 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5440/16794 (completed=5439, failed=1)

2026-08-18 02:11:13 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5460/16794 (completed=5459, failed=1)

2026-08-18 02:11:13 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5480/16794 (completed=5479, failed=1)

2026-08-18 02:11:14 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5500/16794 (completed=5499, failed=1)

2026-08-18 02:11:14 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5520/16794 (completed=5519, failed=1)

2026-08-18 02:11:15 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5540/16794 (completed=5539, failed=1)

2026-08-18 02:11:15 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5560/16794 (completed=5559, failed=1)

2026-08-18 02:11:16 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5580/16794 (completed=5579, failed=1)

2026-08-18 02:11:17 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5600/16794 (completed=5599, failed=1)

2026-08-18 02:11:17 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5620/16794 (completed=5619, failed=1)

2026-08-18 02:11:18 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5640/16794 (completed=5639, failed=1)

2026-08-18 02:11:18 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5660/16794 (completed=5659, failed=1)

2026-08-18 02:11:19 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5680/16794 (completed=5679, failed=1)

2026-08-18 02:11:19 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5700/16794 (completed=5699, failed=1)

2026-08-18 02:11:20 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5720/16794 (completed=5719, failed=1)

2026-08-18 02:11:21 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5740/16794 (completed=5739, failed=1)

2026-08-18 02:11:21 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5760/16794 (completed=5759, failed=1)

2026-08-18 02:11:22 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5780/16794 (completed=5779, failed=1)

2026-08-18 02:11:22 | INFO | deduplication | Deduplication results: {'UNIQUE': 19, 'EXACT_DUPLICATE': 1}

  Progress: 5800/16794 (completed=5799, failed=1)

2026-08-18 02:11:23 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5820/16794 (completed=5819, failed=1)

2026-08-18 02:11:23 | INFO | deduplication | Deduplication results: {'UNIQUE': 19, 'EXACT_DUPLICATE': 1}

  Progress: 5840/16794 (completed=5839, failed=1)

2026-08-18 02:11:24 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5860/16794 (completed=5859, failed=1)

2026-08-18 02:11:25 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5880/16794 (completed=5879, failed=1)

2026-08-18 02:11:25 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5900/16794 (completed=5899, failed=1)

2026-08-18 02:11:26 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5920/16794 (completed=5919, failed=1)

2026-08-18 02:11:27 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5940/16794 (completed=5939, failed=1)

2026-08-18 02:11:27 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5960/16794 (completed=5959, failed=1)

2026-08-18 02:11:28 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 5980/16794 (completed=5979, failed=1)

2026-08-18 02:11:29 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6000/16794 (completed=5999, failed=1)

2026-08-18 02:11:29 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6020/16794 (completed=6019, failed=1)

2026-08-18 02:11:30 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6040/16794 (completed=6039, failed=1)

2026-08-18 02:11:30 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6060/16794 (completed=6059, failed=1)

2026-08-18 02:11:31 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6080/16794 (completed=6079, failed=1)

2026-08-18 02:11:31 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6100/16794 (completed=6099, failed=1)

2026-08-18 02:11:32 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6120/16794 (completed=6119, failed=1)

2026-08-18 02:11:33 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6140/16794 (completed=6139, failed=1)

2026-08-18 02:11:33 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6160/16794 (completed=6159, failed=1)

2026-08-18 02:11:34 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6180/16794 (completed=6179, failed=1)

2026-08-18 02:11:34 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6200/16794 (completed=6199, failed=1)

2026-08-18 02:11:35 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6220/16794 (completed=6219, failed=1)

2026-08-18 02:11:36 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6240/16794 (completed=6239, failed=1)

2026-08-18 02:11:36 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6260/16794 (completed=6259, failed=1)

2026-08-18 02:11:37 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6280/16794 (completed=6279, failed=1)

2026-08-18 02:11:37 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6300/16794 (completed=6299, failed=1)

2026-08-18 02:11:38 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6320/16794 (completed=6319, failed=1)

2026-08-18 02:11:39 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6340/16794 (completed=6339, failed=1)

2026-08-18 02:11:39 | INFO | deduplication | Deduplication results: {'UNIQUE': 19}

  Progress: 6360/16794 (completed=6358, failed=2)

2026-08-18 02:11:40 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6380/16794 (completed=6378, failed=2)

2026-08-18 02:11:40 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6400/16794 (completed=6398, failed=2)

2026-08-18 02:11:41 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6420/16794 (completed=6418, failed=2)

2026-08-18 02:11:42 | INFO | deduplication | Deduplication results: {'UNIQUE': 20}

  Progress: 6440/16794 (completed=6438, failed=2)

Exception during reset or similar
Traceback (most recent call last):
  File "c:\Users\pc\Desktop\Semesters\Semester - IV\Capstone_Project_II\capstone_final_project\Project\.venv\lib\site-packages\sqlalchemy\pool\base.py", line 986, in _finalize_fairy
    fairy._reset(
  File "c:\Users\pc\Desktop\Semesters\Semester - IV\Capstone_Project_II\capstone_final_project\Project\.venv\lib\site-packages\sqlalchemy\pool\base.py", line 1441, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Users\pc\Desktop\Semesters\Semester - IV\Capstone_Project_II\capstone_final_project\Project\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 712, in do_rollback
    dbapi_connection.rollback()
  File "c:\Users\pc\Desktop\Semesters\Semester - IV\Capstone_Project_II\capstone_final_project\Project\.venv\lib\site-packages\pymysql\connections.py", line 511, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "c:\Users\pc\Desktop\Semesters\Semester - IV\Capstone_Project_II\capstone_final_project\Project\.venv\lib\site-packages\pymysql\connections.py", line 886, in _execute_command
    self._write_bytes(packet)
  File "c:\Users\pc\Desktop\Semesters\Semester - IV\Capstone_Project_II\capstone_final_project\Project\.venv\lib\site-packages\pymysql\connections.py", line 834, in _write_bytes
    self._sock.sendall(data)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1206, in send
    return self._sslobj.write(data)
KeyboardInterrupt

KeyboardInterrupt:

In [7]:
import database as db
ids = db.get_unprocessed_article_ids(limit=20)
print(f"Testing on {len(ids)} articles")

# temporarily process just these by calling process_new_article on each
for aid in ids:
    pipeline.process_new_article(aid)

ModuleNotFoundError: No module named 'config'

In [5]:
pipeline.process_existing_articles(batch_size=1000)

2026-08-18 02:14:24 | INFO | pipeline | process_existing_articles: 10338 articles to process
2026-08-18 02:14:46 | INFO | deduplication | Deduplication results: {'UNIQUE': 998}

  Progress: 1000/10338 (completed=998, failed=2)

2026-08-18 02:15:19 | INFO | deduplication | Deduplication results: {'UNIQUE': 998, 'EXACT_DUPLICATE': 2}

  Progress: 2000/10338 (completed=1998, failed=2)

2026-08-18 02:15:50 | INFO | deduplication | Deduplication results: {'UNIQUE': 1000}

  Progress: 3000/10338 (completed=2998, failed=2)

2026-08-18 02:16:24 | INFO | deduplication | Deduplication results: {'UNIQUE': 998, 'EXACT_DUPLICATE': 2}

  Progress: 4000/10338 (completed=3998, failed=2)

2026-08-18 02:16:54 | INFO | deduplication | Deduplication results: {'UNIQUE': 994, 'EXACT_DUPLICATE': 6}

  Progress: 5000/10338 (completed=4998, failed=2)

2026-08-18 02:17:23 | INFO | deduplication | Deduplication results: {'UNIQUE': 992, 'EXACT_DUPLICATE': 7, 'NEAR_DUPLICATE': 1}

  Progress: 6000/10338 (completed=5998, failed=2)

2026-08-18 02:17:52 | INFO | deduplication | Deduplication results: {'UNIQUE': 1000}

  Progress: 7000/10338 (completed=6998, failed=2)

2026-08-18 02:18:21 | INFO | deduplication | Deduplication results: {'UNIQUE': 997, 'EXACT_DUPLICATE': 3}

  Progress: 8000/10338 (completed=7998, failed=2)

2026-08-18 02:18:50 | INFO | deduplication | Deduplication results: {'UNIQUE': 1000}

  Progress: 9000/10338 (completed=8998, failed=2)

2026-08-18 02:19:19 | INFO | deduplication | Deduplication results: {'UNIQUE': 998, 'EXACT_DUPLICATE': 1, 'NEAR_DUPLICATE': 1}

  Progress: 10000/10338 (completed=9998, failed=2)

2026-08-18 02:19:33 | INFO | deduplication | Deduplication results: {'UNIQUE': 337, 'EXACT_DUPLICATE': 1}

  Progress: 10338/10338 (completed=10336, failed=2)

Done. Completed: 10336, Failed validation: 2

In [1]:
import sys, os
sys.path.insert(0, os.path.join(os.getcwd(), '..', 'src'))
sys.path.insert(0, os.path.join(os.getcwd(), '..'))

import sentiment
print(sentiment.__file__)   # confirm this points to your project's src/sentiment.py, not site-packages

c:\Users\pc\Desktop\Semesters\Semester - IV\Capstone_Project_II\capstone_final_project\Project\notebooks\..\src\sentiment.py

In [5]:
sentiment.process_all_sentiment(limit=50)

2026-08-18 03:16:20 | INFO | sentiment | process_all_sentiment: 50 articles to process
c:\Users\pc\Desktop\Semesters\Semester - IV\Capstone_Project_II\capstone_final_project\Project\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-08-18 03:19:25 | INFO | sentiment | Loading sentiment model cardiffnlp/twitter-roberta-base-sentiment-latest (device=CPU)...
c:\Users\pc\Desktop\Semesters\Semester - IV\Capstone_Project_II\capstone_final_project\Project\.venv\lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\pc\.cache\huggingface\hub\models--cardiffnlp--twitter-roberta-base-sentiment-latest. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 4333.07it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.weight | UNEXPECTED |  |
roberta.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-08-18 03:36:40 | INFO | sentiment | Sentiment model loaded.

  Progress: 32/50
  Progress: 50/50

Done. Sentiment computed for 50 articles.

In [2]:
sentiment.process_all_sentiment(batch_size=32)

2026-08-18 11:22:59 | INFO | sentiment | process_all_sentiment: 16742 articles to process
c:\Users\pc\Desktop\Semesters\Semester - IV\Capstone_Project_II\capstone_final_project\Project\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-08-18 11:29:19 | INFO | sentiment | Loading sentiment model cardiffnlp/twitter-roberta-base-sentiment-latest (device=CPU)...
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 4947.16it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.bias   | UNEXPECTED |  |
roberta.pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-08-18 11:29:35 | INFO | sentiment | Sentiment model loaded.

  Progress: 32/16742
  Progress: 64/16742
  Progress: 96/16742
  Progress: 128/16742
  Progress: 160/16742
  Progress: 192/16742
  Progress: 224/16742
  Progress: 256/16742
  Progress: 288/16742
  Progress: 320/16742
  Progress: 352/16742
  Progress: 384/16742
  Progress: 416/16742
  Progress: 448/16742
  Progress: 480/16742
  Progress: 512/16742
  Progress: 544/16742
  Progress: 576/16742
  Progress: 608/16742
  Progress: 640/16742
  Progress: 672/16742
  Progress: 704/16742
  Progress: 736/16742
  Progress: 768/16742
  Progress: 800/16742
  Progress: 832/16742
  Progress: 864/16742
  Progress: 896/16742
  Progress: 928/16742
  Progress: 960/16742
  Progress: 992/16742
  Progress: 1024/16742
  Progress: 1056/16742
  Progress: 1088/16742
  Progress: 1120/16742
  Progress: 1152/16742
  Progress: 1184/16742
  Progress: 1216/16742
  Progress: 1248/16742
  Progress: 1280/16742
  Progress: 1312/16742
  Progress: 1344/16742
  Progress: 1376/16742
  Progress: 1408/16742
  Progress: 1440/16742
  Progress: 1472/16742
  Progress: 1504/16742
  Progress: 1536/16742
  Progress: 1568/16742
  Progress: 1600/16742
  Progress: 1632/16742
  Progress: 1664/16742
  Progress: 1696/16742
  Progress: 1728/16742
  Progress: 1760/16742
  Progress: 1792/16742
  Progress: 1824/16742
  Progress: 1856/16742
  Progress: 1888/16742
  Progress: 1920/16742
  Progress: 1952/16742
  Progress: 1984/16742
  Progress: 2016/16742
  Progress: 2048/16742
  Progress: 2080/16742
  Progress: 2112/16742
  Progress: 2144/16742
  Progress: 2176/16742
  Progress: 2208/16742
  Progress: 2240/16742
  Progress: 2272/16742
  Progress: 2304/16742
  Progress: 2336/16742
  Progress: 2368/16742
  Progress: 2400/16742
  Progress: 2432/16742
  Progress: 2464/16742
  Progress: 2496/16742
  Progress: 2528/16742
  Progress: 2560/16742
  Progress: 2592/16742
  Progress: 2624/16742
  Progress: 2656/16742
  Progress: 2688/16742
  Progress: 2720/16742
  Progress: 2752/16742
  Progress: 2784/16742
  Progress: 2816/16742
  Progress: 2848/16742
  Progress: 2880/16742
  Progress: 2912/16742
  Progress: 2944/16742
  Progress: 2976/16742
  Progress: 3008/16742
  Progress: 3040/16742
  Progress: 3072/16742
  Progress: 3104/16742
  Progress: 3136/16742
  Progress: 3168/16742
  Progress: 3200/16742
  Progress: 3232/16742
  Progress: 3264/16742
  Progress: 3296/16742
  Progress: 3328/16742
  Progress: 3360/16742
  Progress: 3392/16742
  Progress: 3424/16742
  Progress: 3456/16742
  Progress: 3488/16742
  Progress: 3520/16742
  Progress: 3552/16742
  Progress: 3584/16742
  Progress: 3616/16742
  Progress: 3648/16742
  Progress: 3680/16742
  Progress: 3712/16742
  Progress: 3744/16742
  Progress: 3776/16742
  Progress: 3808/16742
  Progress: 3840/16742
  Progress: 3872/16742
  Progress: 3904/16742
  Progress: 3936/16742
  Progress: 3968/16742
  Progress: 4000/16742
  Progress: 4032/16742
  Progress: 4064/16742
  Progress: 4096/16742
  Progress: 4128/16742
  Progress: 4160/16742
  Progress: 4192/16742
  Progress: 4224/16742
  Progress: 4256/16742
  Progress: 4288/16742
  Progress: 4320/16742
  Progress: 4352/16742
  Progress: 4384/16742
  Progress: 4416/16742
  Progress: 4448/16742
  Progress: 4480/16742
  Progress: 4512/16742
  Progress: 4544/16742
  Progress: 4576/16742
  Progress: 4608/16742
  Progress: 4640/16742
  Progress: 4672/16742
  Progress: 4704/16742
  Progress: 4736/16742
  Progress: 4768/16742
  Progress: 4800/16742
  Progress: 4832/16742
  Progress: 4864/16742
  Progress: 4896/16742
  Progress: 4928/16742
  Progress: 4960/16742
  Progress: 4992/16742
  Progress: 5024/16742
  Progress: 5056/16742
  Progress: 5088/16742
  Progress: 5120/16742
  Progress: 5152/16742
  Progress: 5184/16742
  Progress: 5216/16742
  Progress: 5248/16742
  Progress: 5280/16742
  Progress: 5312/16742
  Progress: 5344/16742
  Progress: 5376/16742
  Progress: 5408/16742
  Progress: 5440/16742
  Progress: 5472/16742
  Progress: 5504/16742
  Progress: 5536/16742
  Progress: 5568/16742
  Progress: 5600/16742
  Progress: 5632/16742
  Progress: 5664/16742
  Progress: 5696/16742
  Progress: 5728/16742
  Progress: 5760/16742
  Progress: 5792/16742
  Progress: 5824/16742
  Progress: 5856/16742
  Progress: 5888/16742
  Progress: 5920/16742
  Progress: 5952/16742
  Progress: 5984/16742
  Progress: 6016/16742
  Progress: 6048/16742
  Progress: 6080/16742
  Progress: 6112/16742
  Progress: 6144/16742
  Progress: 6176/16742
  Progress: 6208/16742
  Progress: 6240/16742
  Progress: 6272/16742
  Progress: 6304/16742
  Progress: 6336/16742
  Progress: 6368/16742
  Progress: 6400/16742
  Progress: 6432/16742
  Progress: 6464/16742
  Progress: 6496/16742
  Progress: 6528/16742
  Progress: 6560/16742
  Progress: 6592/16742
  Progress: 6624/16742
  Progress: 6656/16742
  Progress: 6688/16742
  Progress: 6720/16742
  Progress: 6752/16742
  Progress: 6784/16742
  Progress: 6816/16742
  Progress: 6848/16742
  Progress: 6880/16742
  Progress: 6912/16742
  Progress: 6944/16742
  Progress: 6976/16742
  Progress: 7008/16742
  Progress: 7040/16742
  Progress: 7072/16742
  Progress: 7104/16742
  Progress: 7136/16742
  Progress: 7168/16742
  Progress: 7200/16742
  Progress: 7232/16742
  Progress: 7264/16742
  Progress: 7296/16742
  Progress: 7328/16742
  Progress: 7360/16742
  Progress: 7392/16742
  Progress: 7424/16742
  Progress: 7456/16742
  Progress: 7488/16742
  Progress: 7520/16742
  Progress: 7552/16742
  Progress: 7584/16742
  Progress: 7616/16742
  Progress: 7648/16742
  Progress: 7680/16742
  Progress: 7712/16742
  Progress: 7744/16742
  Progress: 7776/16742
  Progress: 7808/16742
  Progress: 7840/16742
  Progress: 7872/16742
  Progress: 7904/16742
  Progress: 7936/16742
  Progress: 7968/16742
  Progress: 8000/16742
  Progress: 8032/16742
  Progress: 8064/16742
  Progress: 8096/16742
  Progress: 8128/16742
  Progress: 8160/16742
  Progress: 8192/16742
  Progress: 8224/16742
  Progress: 8256/16742
  Progress: 8288/16742
  Progress: 8320/16742
  Progress: 8352/16742
  Progress: 8384/16742
  Progress: 8416/16742
  Progress: 8448/16742
  Progress: 8480/16742
  Progress: 8512/16742
  Progress: 8544/16742
  Progress: 8576/16742
  Progress: 8608/16742
  Progress: 8640/16742
  Progress: 8672/16742
  Progress: 8704/16742
  Progress: 8736/16742
  Progress: 8768/16742
  Progress: 8800/16742
  Progress: 8832/16742
  Progress: 8864/16742
  Progress: 8896/16742
  Progress: 8928/16742
  Progress: 8960/16742
  Progress: 8992/16742
  Progress: 9024/16742
  Progress: 9056/16742
  Progress: 9088/16742
  Progress: 9120/16742
  Progress: 9152/16742
  Progress: 9184/16742
  Progress: 9216/16742
  Progress: 9248/16742
  Progress: 9280/16742
  Progress: 9312/16742
  Progress: 9344/16742
  Progress: 9376/16742
  Progress: 9408/16742
  Progress: 9440/16742
  Progress: 9472/16742
  Progress: 9504/16742
  Progress: 9536/16742
  Progress: 9568/16742
  Progress: 9600/16742
  Progress: 9632/16742
  Progress: 9664/16742
  Progress: 9696/16742
  Progress: 9728/16742
  Progress: 9760/16742
  Progress: 9792/16742
  Progress: 9824/16742
  Progress: 9856/16742
  Progress: 9888/16742
  Progress: 9920/16742
  Progress: 9952/16742
  Progress: 9984/16742
  Progress: 10016/16742
  Progress: 10048/16742
  Progress: 10080/16742
  Progress: 10112/16742
  Progress: 10144/16742
  Progress: 10176/16742
  Progress: 10208/16742
  Progress: 10240/16742
  Progress: 10272/16742
  Progress: 10304/16742
  Progress: 10336/16742
  Progress: 10368/16742
  Progress: 10400/16742
  Progress: 10432/16742
  Progress: 10464/16742
  Progress: 10496/16742
  Progress: 10528/16742
  Progress: 10560/16742
  Progress: 10592/16742
  Progress: 10624/16742
  Progress: 10656/16742
  Progress: 10688/16742
  Progress: 10720/16742
  Progress: 10752/16742
  Progress: 10784/16742
  Progress: 10816/16742
  Progress: 10848/16742
  Progress: 10880/16742
  Progress: 10912/16742
  Progress: 10944/16742
  Progress: 10976/16742
  Progress: 11008/16742
  Progress: 11040/16742
  Progress: 11072/16742
  Progress: 11104/16742
  Progress: 11136/16742
  Progress: 11168/16742
  Progress: 11200/16742
  Progress: 11232/16742
  Progress: 11264/16742
  Progress: 11296/16742
  Progress: 11328/16742
  Progress: 11360/16742
  Progress: 11392/16742
  Progress: 11424/16742
  Progress: 11456/16742
  Progress: 11488/16742
  Progress: 11520/16742
  Progress: 11552/16742
  Progress: 11584/16742
  Progress: 11616/16742
  Progress: 11648/16742
  Progress: 11680/16742
  Progress: 11712/16742
  Progress: 11744/16742
  Progress: 11776/16742
  Progress: 11808/16742
  Progress: 11840/16742
  Progress: 11872/16742
  Progress: 11904/16742
  Progress: 11936/16742
  Progress: 11968/16742
  Progress: 12000/16742
  Progress: 12032/16742
  Progress: 12064/16742
  Progress: 12096/16742
  Progress: 12128/16742
  Progress: 12160/16742
  Progress: 12192/16742
  Progress: 12224/16742
  Progress: 12256/16742
  Progress: 12288/16742
  Progress: 12320/16742
  Progress: 12352/16742
  Progress: 12384/16742
  Progress: 12416/16742
  Progress: 12448/16742
  Progress: 12480/16742
  Progress: 12512/16742
  Progress: 12544/16742
  Progress: 12576/16742
  Progress: 12608/16742
  Progress: 12640/16742
  Progress: 12672/16742
  Progress: 12704/16742
  Progress: 12736/16742
  Progress: 12768/16742
  Progress: 12800/16742
  Progress: 12832/16742
  Progress: 12864/16742
  Progress: 12896/16742
  Progress: 12928/16742
  Progress: 12960/16742
  Progress: 12992/16742
  Progress: 13024/16742
  Progress: 13056/16742
  Progress: 13088/16742
  Progress: 13120/16742
  Progress: 13152/16742
  Progress: 13184/16742
  Progress: 13216/16742
  Progress: 13248/16742
  Progress: 13280/16742
  Progress: 13312/16742
  Progress: 13344/16742
  Progress: 13376/16742
  Progress: 13408/16742
  Progress: 13440/16742
  Progress: 13472/16742
  Progress: 13504/16742
  Progress: 13536/16742
  Progress: 13568/16742
  Progress: 13600/16742
  Progress: 13632/16742
  Progress: 13664/16742
  Progress: 13696/16742
  Progress: 13728/16742
  Progress: 13760/16742
  Progress: 13792/16742
  Progress: 13824/16742
  Progress: 13856/16742
  Progress: 13888/16742
  Progress: 13920/16742
  Progress: 13952/16742
  Progress: 13984/16742
  Progress: 14016/16742
  Progress: 14048/16742
  Progress: 14080/16742
  Progress: 14112/16742
  Progress: 14144/16742
  Progress: 14176/16742
  Progress: 14208/16742
  Progress: 14240/16742
  Progress: 14272/16742
  Progress: 14304/16742
  Progress: 14336/16742
  Progress: 14368/16742
  Progress: 14400/16742
  Progress: 14432/16742
  Progress: 14464/16742
  Progress: 14496/16742
  Progress: 14528/16742
  Progress: 14560/16742
  Progress: 14592/16742
  Progress: 14624/16742
  Progress: 14656/16742
  Progress: 14688/16742
  Progress: 14720/16742
  Progress: 14752/16742
  Progress: 14784/16742
  Progress: 14816/16742
  Progress: 14848/16742
  Progress: 14880/16742
  Progress: 14912/16742
  Progress: 14944/16742
  Progress: 14976/16742
  Progress: 15008/16742
  Progress: 15040/16742
  Progress: 15072/16742
  Progress: 15104/16742
  Progress: 15136/16742
  Progress: 15168/16742
  Progress: 15200/16742
  Progress: 15232/16742
  Progress: 15264/16742
  Progress: 15296/16742
  Progress: 15328/16742
  Progress: 15360/16742
  Progress: 15392/16742
  Progress: 15424/16742
  Progress: 15456/16742
  Progress: 15488/16742
  Progress: 15520/16742
  Progress: 15552/16742
  Progress: 15584/16742
  Progress: 15616/16742
  Progress: 15648/16742
  Progress: 15680/16742
  Progress: 15712/16742
  Progress: 15744/16742
  Progress: 15776/16742
  Progress: 15808/16742
  Progress: 15840/16742
  Progress: 15872/16742
  Progress: 15904/16742
  Progress: 15936/16742
  Progress: 15968/16742
  Progress: 16000/16742
  Progress: 16032/16742
  Progress: 16064/16742
  Progress: 16096/16742
  Progress: 16128/16742
  Progress: 16160/16742
  Progress: 16192/16742
  Progress: 16224/16742
  Progress: 16256/16742
  Progress: 16288/16742
  Progress: 16320/16742
  Progress: 16352/16742
  Progress: 16384/16742
  Progress: 16416/16742
  Progress: 16448/16742
  Progress: 16480/16742
  Progress: 16512/16742
  Progress: 16544/16742
  Progress: 16576/16742
  Progress: 16608/16742
  Progress: 16640/16742
  Progress: 16672/16742
  Progress: 16704/16742
  Progress: 16736/16742
  Progress: 16742/16742

Done. Sentiment computed for 16742 articles.

In [3]:
df = sentiment.get_sentiment_eval_sample(n=120)
df.to_csv('../data/processed/sentiment_eval_sample.csv', index=False)

In [5]:
import pandas as pd
import sys, os
sys.path.insert(0, os.path.join(os.getcwd(), '..', 'src'))
import database as db
from sqlalchemy import text

df = pd.read_csv('../data/processed/sentiment_eval_sample.csv')

with db.get_connection() as conn:
    sentiment_df = pd.read_sql(text("SELECT article_id, sentiment FROM article_sentiment"), conn)

df = df.merge(sentiment_df, on='article_id', how='left')
df.to_csv('../data/processed/sentiment_eval_sample.csv', index=False)

In [6]:
import evaluate_sentiment
results = evaluate_sentiment.run('../data/processed/sentiment_eval_sample.csv')

ValueError: CSV doesn't have a 'sentiment' column (the model's prediction). If get_sentiment_eval_sample() only pulled from processed_news, you need to join in article_sentiment.sentiment first — see the join snippet in the message below this script.

In [9]:
import sys, os
sys.path.insert(0, os.path.join(os.getcwd(), '..', 'src'))
sys.path.insert(0, os.path.join(os.getcwd(), '..'))

import topics
model, topic_info = topics.process_all_topics(limit=1000)

2026-08-18 13:58:57 | INFO | topics | process_all_topics: fitting on 1000 articles
c:\Users\pc\Desktop\Semesters\Semester - IV\Capstone_Project_II\capstone_final_project\Project\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-08-18 14:02:59 | INFO | topics | Loading embedding model all-MiniLM-L6-v2...
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2146.21it/s]
2026-08-18 14:07:07 | INFO | topics | Embedding model loaded.
2026-08-18 14:07:07 | INFO | topics | Encoding 1000 documents...
Batches: 100%|██████████| 32/32 [00:36<00:00,  1.14s/it]
2026-08-18 14:07:44 | INFO | topics | Fitting BERTopic model...
2026-08-18 14:07:44,317 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-08-18 14:08:22,638 - BERTopic - Dimensionality - Completed ✓
2026-08-18 14:08:22,653 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-08-18 14:08:23,115 - BERTopic - Cluster - Completed ✓
2026-08-18 14:08:23,323 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-08-18 14:08:23,812 - BERTopic - Representation - Completed ✓
2026-08-18 14:08:24 | INFO | topics | Fitting complete. Found 16 topics (+ outliers if any).
2026-08-18 14:08:26 | INFO | topics | Model saved to c:\Users\pc\Desktop\Semesters\Semester - IV\Capstone_Project_II\capstone_final_project\Project\notebooks\..\src\..\models\topics\bertopic_model
2026-08-18 14:08:26 | INFO | topics | Topic info saved to c:\Users\pc\Desktop\Semesters\Semester - IV\Capstone_Project_II\capstone_final_project\Project\notebooks\..\src\..\models\topics\topic_info.csv — review this to decide on manual names.

Done. 1000 articles assigned to 17 topics (including outliers if present).

Top topics by article count:
 Topic  Count                                Name                                                                     Representation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Representative_Docs
    -1    207                    -1_the_to_and_in                                [the, to, and, in, of, on, has, for, sri, minister] [US$2.5Mn cyber heist; COPF covers up the top brass: UNP The United National Party (UNP) yesterday charged that the Committee on Public Finance (COPF) had failed to identify the shortcomings of senior officials in connection with the cybercrime, while highlighting that the US$2.5 million heist had occurred due to the failure of the Finance Minister and the Secretary to the Finance Ministry to monitor the transition of powers from the Central Bank to the Public Debt Management Office., Early optimism gives way to weaker close at the CSE The Colombo Stock Exchange (CSE) closed lower on Friday as early buying interest gave way to profit-taking in several index-heavy counters, pushing both benchmark indices into negative territory by the end of the session. While the market opened on a positive note with broad-based buying across counters, selling pressure intensified during the latter half of trading, erasing the morning's gains., I will come back to Parliament in 2029 and make sure that Minister Harshana Nanayakkara in prison: Archchuna Justice Minister Harshana Nanayakkara was asleep after a booze at the time of the clash in Negombo Prison, Independent MP Ramanathan Archchuna alleged in Parliament yesterday.]
     0    134            0_arrested_of_the_former                     [arrested, of, the, former, police, in, over, to, court, been]                                                                                                                                                                                                                                                [Ex-Police Chief, Defence Secretary taken to prison after death sentence Former Inspector General of Police (IGP) Pujith Jayasundara and former Defence Secretary Hemasiri Fernando were taken to prison on Friday after the Colombo Permanent High Court Trial-at-Bar sentenced them to death over their failure to prevent the 2019 Easter Sunday terrorist attacks despite receiving prior intelligence warnings., Former State Minister's son arrested over Rs. 20M robbery The son of former State Minister Shanta Bandara has been arrested by the Colpetty Police in connection with the alleged robbery of Rs. 20 million belonging to a Chinese national., Why was Akila Kariyawasam arrested? Former Minister Akila Viraj Kariyawasam was arrested today by officers of the Commission to Investigate Allegations of Bribery or Corruption (CIABOC) over allegations that he misused state-funded employees for personal purposes while serving as the Senior Adviser to the President on Administrative Affairs.]
     1     98               1_in_killed_at_people                  [in, killed, at, people, after, least, on, injured, shooting, of]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [At least 132 killed in Colombia's largest earthquake in years At least 132 people are dead and a state of emergency has been declared after Colombia was hit by one of its largest earthquakes in years., Twelve killed and at least 10 injured in Polish bus crash in Hungary A dozen people were killed and at least 10 injured ​after a Polish bus overturned at night on a motorway ‌in eastern Hungary, Hungarian Prime Minister Peter Magyar said on Sunday morning in a Facebook post., At least 25 people killed in Algeria bus crash At least 25 people have been killed and dozens of others injured in Algeria after a passenger bus overturned near the coastal town of Boumerdes, east of the capital Algiers, on Friday, local officials said.]
     2     67         2_judges_retirement_age_the          [judges, retirement, age, the, basl, amendment, of, to, extend, proposed]                                                                                                                                                                                                                                                [BASL was not consulted on proposed judges' retirement age amendment: BASL President Bar Association of Sri Lanka (BASL) President Rajeev Amarasuriya today said the BASL had not been consulted before the Government proceeded with the proposed constitutional amendment seeking to extend the retirement age of judges., Mahanayake Theras oppose proposal to extend judges' retirement age: BASL President The Mahanayake Theras of the three Buddhist chapters have written to President Anura Kumara Dissanayake stating that the proposed constitutional amendment to extend the retirement age of judges is inappropriate, President of the Bar Association of Sri Lanka (BASL) Rajeev Amarasuriya said., BASL seeks meeting with President over judges' retirement age amendment The Bar Association of Sri Lanka (BASL) has formally requested a meeting with President Anura Kumara Dissanayake to discuss the Government's proposed constitutional amendment seeking to increase the retirement age of judges.]
     3     61                  3_sri_the_lanka_to                        [sri, the, lanka, to, of, lankas, in, vehicle, us, billion]                     [How Sri Lanka missed the opportunity to become a 200 billion dollar economy For the first time in history, Sri Lankan economy surpassed the hundred billion dollar mark in 2025. Gross Domestic Product ("GDP") and GDP per capita reached USD 109 billion and USD 5,003 respectively in 2025. Interestingly, Sri Lanka was an 85 billion economy way back in 2015, and it took a decade to surpass the hundred billion dollar benchmark. This suggests a decade of slow economic progress., Sri Lanka's foreign remittances surpass US$5 Billion in first seven months Sri Lanka's foreign remittances from overseas workers have surpassed US$5 billion during the first seven months of 2026, according to data released by the Central Bank of Sri Lanka., Will the "tax shock" kill the Sri Lankan economy? Under the latest IMF extended fund facility program, Sri Lanka has achieved substantial increase in tax revenue – to a level never seen in the history. Data show that for the first quarter of 2026, tax collections increased by an impressive 49 percent compared to same period last year. With GDP growing at 5.1 percent, and inflation below 2.5 percent, first quarter economic performance looks good on "IMF report card!"]
     4     56             4_areas_the_water_heavy     [areas, the, water, heavy, department, issued, to, and, meteorology, rainfall]                                                                                                                                                                                                                                                                                                                                                                                     [Major flood warning issued for Kelani River Valley The Irrigation Department has issued a major flood warning for low-lying areas of the Kelani River Valley, stating that a major flood situation could develop within the next 24 hours due to heavy rainfall in the upper and middle catchment areas of the river basin., Strong winds, heavy rains in several areas today The Meteorology Department issued a strong wind advisory for the Northern, North-Central, North-Western, Sabaragamuwa and Central Provinces and the Moneragala, Hambantota and Trincomalee districts for 24 hours starting from 11 am today., Strong winds forecast over several areas; public urged to take precautions The Department of Meteorology has issued a warning of strong winds over several parts of the country and the surrounding sea areas due to active southwest monsoon conditions.]
     5     54           5_the_cricket_world_lanka            [the, cricket, world, lanka, test, sri, 2026, in, league, commonwealth]                                                                                                                                          [LPL 2026 Playoff Race Heats Up LPL 2026 heads into its decisive final league stage as the race for the playoffs intensifies. Galle Gallants remain on top of the standings, while Colombo Kaps, Jaffna Kings, Dambulla Sixers and Kandy Royals continue battling for the remaining top-four spots. With six league matches left at the Pallekele International Cricket Stadium before the tournament moves to Colombo for the playoffs, every result could reshape the standings., Galle Gallants Crowned LPL 2026 Champions Galle Gallants secured their maiden Lanka Premier League (LPL) title with a convincing five-wicket victory over Jaffna Kings in a low-scoring final at the R. Premadasa International Cricket Stadium in Colombo., Dikwella makes Test return as Sri Lanka name India squad Sri Lanka Cricket's Selection Committee has announced a 16-member squad for the first Test of the upcoming two-match series against India. The opening match, part of the ICC World Test Championship 2025–2027 cycle, is scheduled to be played at the Galle International Cricket Stadium from August 15 to 19, 2026.]
     6     47                  6_iran_us_trump_on                     [iran, us, trump, on, strikes, donald, says, oil, war, hormuz]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     [Trump says he will declare Strait of Hormuz a US 'territory' amid Iran war Control over the waterway has been a sticking point in negotiations between the US and Iran, with Trump's comments likely to inflame tensions., Trump says US strikes hit Iran in 'honour' of American soldiers killed President Donald Trump says the latest strikes by the US hit Iran ''very hard'', adding that the attacks were ''in honour'' of three US soldiers killed in recent days - two in Jordan, one in Iraq., US launches 'heavy' strikes on Iran after attempted attack on American troops The US military says it launched ''heavy'' strikes against Iran on Wednesday in retaliation for attempted Iranian ballistic missile attacks on American forces.]
     7     43        7_president_of_appointed_the          [president, of, appointed, the, kumara, dissanayake, anura, new, to, sri]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [Lieutenant General Nilantha Premaratne appointed new Army Commander Lieutenant General Nilantha Premaratne has been appointed as the 26th Commander of the Sri Lanka Army by President Anura Kumara Dissanayake., New Chairman and members appointed to Delimitation Commission President Anura Kumara Dissanayake has appointed M. K. Saman Sri Ratnayake as the new Chairman and a member of the Delimitation Commission., President discusses issues in developing cricket in Sri Lanka President Anura Kumara Dissanayake held a meeting with the Sri Lanka Cricket (SLC)]
     8     41              8_to_the_transport_sri                  [to, the, transport, sri, of, approved, cabinet, new, lanka, for]                                                                                                                                                                                                                                                                        [RDA tender process under fire As Sri Lanka moves ahead with the Central Expressway Project (CEP 4) and the Ruwanpura Expressway, a senior engineer involved in the project has questioned why the Road Development Authority (RDA), the Ministry of Transport and Highways, and the National Procurement Commission have not allowed proper competition to be followed in the tender process., SLTB to get 600 new deluxe AC buses for intercity travel The Cabinet of Ministers has approved the procurement of 600 deluxe air-conditioned buses for the Sri Lanka Transport Board (SLTB) to upgrade intercity and long-distance passenger transport services., Cabinet approves Rs. 15 Bn for phase 1 of Ruwanpura Expressway The Cabinet of Ministers has granted approval to a proposal presented by the Minister of Transport, Highways, and Urban Development to implement the procurement process and select a suitable contractor for the first phase of the Ruwanpura Expressway Project.]
     9     38 9_animal_welfare_elephants_elephant [animal, welfare, elephants, elephant, to, bill, the, for, humanelephant, animals]                                                                                                                                                                                                                                                                                                                                                                                  [New Animal Welfare Bill: Rs. 250,000 fine, two-year jail for animal cruelty Those convicted of animal cruelty could face fines of up to Rs. 250,000, imprisonment for up to two years, or both, under Sri Lanka's long-awaited Animal Welfare Bill, which has now been published in the Government Gazette., Veterinarians urge swift passage of Animal Welfare Act The Association of Veterinarians for Humane Management of Animal Population has urged authorities not to further delay the enactment of the Animal Welfare Act, warning that continued delays would prolong the suffering of animals., Will proposed Animal Welfare Bill ban elephants in peraheras? Claims that the proposed Animal Welfare Act would prohibit elephants from participating in cultural processions or completely ban the chaining of elephants are false, the Animal Welfare Coalition (AWC) said.]
    10     31            10_fined_caa_rs_consumer             [fined, caa, rs, consumer, selling, rice, above, for, affairs, 500000]                                                                                                                                                                                                                                                                                                           [CAA warns private hospitals against overcharging for FBC, Dengue tests The Consumer Affairs Authority (CAA) has reminded private hospitals and laboratories that maximum charges remain in force for certain medical laboratory tests, following reports that a private hospital in Jaffna had allegedly charged above the approved fee for a Full Blood Count (FBC) test., Supermarket fined Rs. 500,000 for selling Nadu rice above control price A supermarket in Gampola has been fined Rs. 500,000 after pleading guilty to selling local Nadu rice above the government-controlled maximum retail price, the Consumer Affairs Authority (CAA) said., Rice supplier fined Rs. 1 mn for selling Red Nadu above MRP A rice supplier has been fined Rs. 1 million by the Polonnaruwa Magistrate's Court after being found guilty of selling Red Nadu rice above the government-imposed Maximum Retail Price (MRP), the Consumer Affairs Authority (CAA) said.]
    11     29     11_prison_unrest_mahara_inmates  [prison, unrest, mahara, inmates, prisons, at, police, the, security, pallansena]                                                                                                                                                                                                                                                                                                                                                                                      [Security tightened across all prisons following Mahara Prison unrest Authorities have stepped up security at prisons across the country after the violent unrest at the Mahara Prison left one inmate dead, several others injured, and caused extensive damage to prison property., Mahara Prison situation brought under control; 104 inmates transferred The unrest that erupted inside the Mahara Prison on Saturday afternoon has been brought under control through a joint operation involving prison officials, the Sri Lanka Police, the Police Special Task Force (STF) and the Tri-Forces, the Department of Prisons said., Mahara Prison begins transferring inmates after violent unrest The Department of Prisons said a number of inmates from Mahara Prison are being transferred to other prisons following the unrest that erupted at the facility yesterday (01).]

In [10]:
model, topic_info = topics.process_all_topics()

2026-08-18 14:13:09 | INFO | topics | process_all_topics: fitting on 16792 articles
2026-08-18 14:13:09 | INFO | topics | Encoding 16792 documents...
Batches: 100%|██████████| 525/525 [10:29<00:00,  1.20s/it]
2026-08-18 14:23:39 | INFO | topics | Fitting BERTopic model...
2026-08-18 14:23:39,433 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-08-18 14:24:45,977 - BERTopic - Dimensionality - Completed ✓
2026-08-18 14:24:45,979 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-08-18 14:25:48,725 - BERTopic - Cluster - Completed ✓
2026-08-18 14:25:48,740 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-08-18 14:25:51,503 - BERTopic - Representation - Completed ✓
2026-08-18 14:25:53 | INFO | topics | Fitting complete. Found 213 topics (+ outliers if any).
2026-08-18 14:26:11 | INFO | topics | Model saved to c:\Users\pc\Desktop\Semesters\Semester - IV\Capstone_Project_II\capstone_final_project\Project\notebooks\..\src\..\models\topics\bertopic_model
2026-08-18 14:26:12 | INFO | topics | Topic info saved to c:\Users\pc\Desktop\Semesters\Semester - IV\Capstone_Project_II\capstone_final_project\Project\notebooks\..\src\..\models\topics\topic_info.csv — review this to decide on manual names.

Done. 16792 articles assigned to 214 topics (including outliers if present).

Top topics by article count:
 Topic  Count                                      Name                                                                                              Representation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Representative_Docs
    -1   5635                          -1_to_in_the_and                                                       [to, in, the, and, of, sri, for, minister, lanka, on]                                                                                                                         [People gather at several places in Colombo in support of Ranil People have gathered at several places in Colombo in support of former President Ranil Wickremesinghe as his case is to be taken up today., Pentagon wants $200 billion for Iran war. It's nearly 50% of Tehran's GDP The Pentagon is reportedly seeking over $200 billion from the US Congress to fund President Donald Trump's war of choice in Iran. If approved, the war funds will boost the US military campaign that began on February 28 and ramp up the production of weapons used during the conflict, according to a report by The Washington Post., There are other offenders in addition to Rajapaksas: Ranil Referring to the recent judgment given by the Supreme Court where former Presidents Gotabaya Rajapaksa, Mahinda Rajapaksa former Minister Basil Rajapaksa and others were held responsible for the economic crisis, President Ranil Wickremesinghe today said one has to look into whether others are also responsible for the economic debacle and have engaged in a breach of public trust.]
     0    209                      0_cup_win_world_runs                                 [cup, win, world, runs, england, t20, series, victory, bangladesh, wickets]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [India beat New Zealand by 70 runs to reach World Cup final Virat Kohli scored a record-breaking 50th one-day international hundred and Mohammed Shami took seven wickets as India beat New Zealand by 70 runs to reach the Cricket World Cup final on Wednesday., India edge England to reach T20 World Cup Final India beat England by seven runs in a high-scoring semi-final of the ICC Men's T20 World Cup, securing their place in the final after holding off a superb century from Jacob Bethell., India beat Bangladesh to reach Asia Cup final Defending champions India booked their spot in the Asia Cup final with a 41-run victory over Bangladesh.]
     1    203         1_doctors_medical_health_hospital                    [doctors, medical, health, hospital, medicines, hospitals, shortage, dr, medicine, nmra] [NMRA decisions could jeopardise quality of eye drugs in state hospitals: Dr. Sanjeewa President of the Medical and Civil Rights Doctors' Trade Union Alliance, Dr. Chamal Sanjeewa, has alleged that arbitrary decision-making by the National Medicines Regulatory Authority (NMRA) could lead to questionable quality eye medications entering the State hospital system., 25 specialists leave annually, hospitals under strain: Dr. Chamal Sanjeewa says Sri Lanka's healthcare system is grappling with a growing shortage of specialist doctors, as around 25 leave the country each year, severely impacting hospitals across the island, warns Specialist Dr. Chamal Sanjeewa, Chairman of the Medical and Civil Rights Doctors' Trade Union Alliance., Patients forced to pay triple the cost for essential medicines due to shortages, claims Doctors' Union The President of the Medical and Civil Rights Doctors' Trade Union Alliance, Dr. Chamal Sanjeewa, has alleged that shortages of medicines and surgical equipment in government hospitals and the private healthcare sector have led to patients facing exorbitant costs when purchasing essential medical supplies from private vendors.]
     2    198              2_shooting_shot_injured_dead                                 [shooting, shot, injured, dead, police, man, killed, incident, gunman, was]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               [Man injured in shooting at Kohuwala A 25-year-old man was injured following a shooting incident between Nugegoda and Kohuwala junction this evening, police said., One killed, another injured in shooting near Wennappuwa Police Station A shooting incident this morning on Wewa Road, near the Wennappuwa Police Station, left one person dead and another injured., Bondi Beach shooting: At least 10 killed and several injured in park attack Police say at least 10 people have been killed in a shooting near a Jewish gathering at Sydney's Bondi Beach.]
     3    184             3_court_appeal_petition_filed                            [court, appeal, petition, filed, supreme, case, fixed, writ, challenging, order]                                                                                                                                                                                                                                                                                                 [Judgment on Diana's citizenship case to be delivered in due course The Supreme Court today concluded the hearing of the appeal petition filed challenging the Court of Appeal decision to dismiss a writ petition which challenged the legality of State Minister Diana Gamage's parliamentary seat., Gotabaya's writ petition fixed for tomorrow The writ petition filed by former President Gotabaya Rajapaksa seeking an order preventing his arrest in connection with the ongoing investigations into the 2019 Easter Sunday terror attacks was today fixed for tomorrow by the Court of Appeal., SC fixes date for hearing of appeal on Diana's citizenship case The Supreme Court today fixed a date for the hearing of the appeal petition filed challenging the Court of Appeal decision to dismiss a writ petition which challenged the legality of State Minister Diana Gamage's parliamentary seat.]
     4    177            4_namal_slpp_podujana_peramuna                   [namal, slpp, podujana, peramuna, rajapaksa, organizer, mp, opposition, organiser, rally]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [Namal urges SLPP leaders to support weather-affected communities Sri Lanka Podujana Peramuna (SLPP) National Organizer Namal Rajapaksa has urged all SLPP Electoral Organizers and Village Leaders to extend their fullest support to communities affected by the ongoing adverse weather., Take the disaster seriously: Namal Sri Lanka Podujana Peramuna (SLPP) MP Namal Rajapaksa today urged the government to be more serious and focus on providing relief to the disaster affected people., Namal appointed SLPP National Organizer Sri Lanka Podujana Peramuna (SLPP), at its Executive Committee meeting, appointed MP Namal Rajapaksa as the national organizer of the party.]
     5    174              5_day_special_traffic_sacred                                  [day, special, traffic, sacred, relics, vesak, plan, holiday, esala, poya]                                                                                                                                                                                                                                                                                                                                                                              [Special traffic plan in Colombo for 'Walk for Peace' programme The Colombo Traffic Division has announced a special traffic plan to facilitate the 'Walk for Peace' programme scheduled to be held in Colombo tomorrow (28)., Special traffic plan for exposition of sacred relics at Gangaramaya A special traffic management and security plan will be implemented in and around the Hunupitiya Gangaramaya Temple in Colombo in view of the exposition of sacred relics brought from India., Special traffic and security plan in place in Colombo for sacred relic exposition The Sri Lanka Police have announced a comprehensive security and traffic plan in conjunction with the exposition of Devnimori relics of Lord Buddha, which have been brought from India to mark the 78th National Independence Day celebrations.]
     6    173            6_slc_cricket_sports_committee                           [slc, cricket, sports, committee, interim, roshan, ranasinghe, shammi, icc, slmc]                                                                                                                                                                 [SLC Case: Harin urges court to recognise him as Sports Minister Newly appointed Sports Minister Harin Fernando today moved the Court of Appeal that he be recognised as the Sports Minister in connection with the writ petition filed over the Sri Lanka Cricket (SLC) interim committee., Cabinet takes charge of SLC's future interim committee appointments Amidst the recent dispute between President Ranil Wickremesinghe and Sports Minister Roshan Ranasinghe over the appointment of an interim committee for Sri Lanka Cricket (SLC), the Cabinet has decided that any future interim committee appointments for SLC must receive Cabinet approval., Sri Lanka Cricket board suspended; Arjuna Ranatunga appointed as Chairman of Interim Committee Following growing calls to sack the committee of Sri Lanka Cricket (SLC), the SLC board has been suspended and an interim committee led by Arjuna Ranatunga has been appointed by Sports Minister Roshan Ranasinghe, to address the ongoing challenges within Sri Lanka Cricket.]
     7    167   7_elephant_wild_elephants_humanelephant     [elephant, wild, elephants, humanelephant, wildlife, conflict, dehiwala, zoo, zoological, conservation]                                                                                                                                                                            [Jumbo deaths continue, wild elephant electrocuted The death of another wild elephant in the human-elephant conflict was reported yesterday from Handapanagala in Moneragala. The wild elephant that roamed into the village had been electrocuted when it attempted to enter a cultivated land at Kottagashandiya area in Handapanagala. The carcass had been recovered by the wildlife officers who arrived on information from the residents of the area., Over 100 Wild Elephant deaths in four months: One death a day The human–elephant conflict in Sri Lanka has claimed the lives of 143 people and elephants as of April 25 this year, data revealed., Increase in young male elephants linked to rising elephant conflicts: Wildlife Dept. The number of juvenile (young male elephants) in Sri Lanka has increased over the past three national elephant surveys, contributing to a rise in elephant–elephant conflict, Acting Director General of the Wildlife Conservation Department Ranjan Marasinghe said yesterday.]
     8    165       8_tourism_arrivals_tourist_tourists                        [tourism, arrivals, tourist, tourists, destination, sltda, ranked, sri, lanka, mark]                                                                                                                                                                                                                                                                                                                                                                                                                                               [Sri Lanka tourist arrivals top one million mark Sri Lanka's tourism industry has surpassed the one-million visitor mark, recording 1,022,022 tourist arrivals during the first five months of 2026, according to the Sri Lanka Tourism Development Authority (SLTDA)., Sri Lanka records 1.3 million tourist arrivals in 2025 Sri Lanka has welcomed over 1.3 million tourists so far this year, according to data from the Sri Lanka Tourism Development Authority (SLTDA)., Tourist arrivals cross 1.1 million mark Sri Lanka has recorded more than 1.1 million tourist arrivals between January 1 and June 21 this year, reflecting the continued recovery of the country's tourism sector, according to the Sri Lanka Tourism Development Authority (SLTDA).]
     9    161                   9_away_dies_died_passed                                       [away, dies, died, passed, passes, aged, age, veteran, actor, singer]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      [Railways chief passes away The General Manager of Railways, H.M.K.W. Bandara passed away this morning due to a sudden illness at the Anuradhapura Hospital., Veteran singer Mariazelle Goonetilleke passes away Veteran Sri Lankan singer Mariazelle Goonetilleke has passed away at the age of 68. She passed away in the early hours of Friday (July 10) while receiving treatment for an illness at the Colombo South Teaching Hospital in Kalubowila., Veteran singer Athula Sri Gamage passes away Veteran singer Athula Sri Gamage, aged 60, passed away while receiving treatment at the Sri Jayawardenepura General Hospital, family sources said.]
    10    153            10_train_railway_line_railways                 [train, railway, line, railways, services, upcountry, station, disrupted, trains, derailed]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [Upcountry train services restored Train operations on the upcountry railway line, which were disrupted due to fallen trees and a landslide between Idalgashinna and Ohiya railway stations, have been restored, the Sri Lanka Railways Department said today., Fuel train derails, disrupting main line operations Train services on Sri Lanka's Main Line were disrupted this morning (02) following the derailment of a fuel transport train, Sri Lanka Railways announced., Up-country train services disrupted A train derailment was reported on the up-country railway line causing disruptions to services, the Railways Department said.]
    11    143           11_vehicles_vehicle_imports_byd                [vehicles, vehicle, imports, byd, electric, import, importers, customs, imported, surcharge]                                                                                                                                                                                                                                                                                                                            [John Keells responds to claims over BYD vehicle imports In response to recent media reports and rising public concern over a consignment of BYD electric vehicles imported into Sri Lanka, John Keells CG Auto (Pvt) Ltd (JKCG) has clarified that the vehicles in question were brought in directly from BYD in China and are fully compliant with all local regulations., 2.5% tax on imported vehicles to take effect from April 1 The Vehicle Importers' Association of Sri Lanka (VIASL) has announced that a 2.5% tax will be imposed on imported vehicles starting from April 1, 2026., Vehicle prices to surge as 50% import duty surcharge extended Vehicle prices are set to rise further following the Government's decision to extend the 50% surcharge imposed on vehicle import duties until December 31, the Vehicle Importers Association of Sri Lanka (VIASL) said.]

In [4]:
import sys, os
sys.path.insert(0, os.path.join(os.getcwd(), '..', 'src'))
sys.path.insert(0, os.path.join(os.getcwd(), '..'))